site_name: StarlingX Documentation
nav:
  - Home: index.md
  - Giới thiệu:
      - "Giới thiệu": introduction/introduction.md
      - "Các khối chức năng chính": introduction/funtional-overview.md
      - "Các mô hình triển khai": introduction/DeploymentConfigurationsOverview.md
      - "Các thuật ngữ chính": introduction/BasicTerminology.md
      - "Cách sử dụng StarlingX": introduction/consuming-starlingx.md
      - "Tổng hợp về dự án StarlingX": introduction/starlingx-project-overview.md
      - "Project": introduction/projects.md
  - Cấu hình triển khai:
      - "Các lựa chọn triển khai": deployment-configuration/deployment-options.md
      - "All-in-One Simplex": deployment-configuration/all-in-one-simplex.md
      - "All-in-One Duplex": deployment-configuration/all-in-one-duplex.md
      - "Standard Configuration with Controller Storage": deployment-configuration/standard-controller-storage.md
      - "standard Configuration with Dedicated Storage": deployment-configuration/standard-dedicated-storage.md
  - Kế hoạch triển khai nền tảng StarlingX:
      - "Kubernetes": planning/kubernetes.md
      - "OpenStack": planning/openstack.md
  - Cài đặt và cấu hình:
      - "Tổng quan": installation/overview.md
      - "Chuẩn bị môi trường": installation/prepare.md
      - "Chuẩn bị cài đặt": installation/install-virtualbox.md
      - "Cài đặt StarlingX": installation/install-starlingx.md
      - "Bootstrapping": installation/install-bootstrap.md


